name: Generate SBOM

on:
  push:
    branches: [ master ]

jobs:
  generate-sbom:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install CycloneDX SBOM Generator
        run: npm install -g @cyclonedx/bom

      - name: Generate SBOM
        run: cyclonedx-bom -o sbom.json

      - name: Upload SBOM
        uses: actions/upload-artifact@v3
        with:
          name: sbom
          path: sbom.json
